#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spar.Gateway.VendorList
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Spar")]
	public partial class WarehouseVendorsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    partial void InsertSupplierWarehouse(SupplierWarehouse instance);
    partial void UpdateSupplierWarehouse(SupplierWarehouse instance);
    partial void DeleteSupplierWarehouse(SupplierWarehouse instance);
    partial void InsertSupplierDCLookupWarehouse(SupplierDCLookupWarehouse instance);
    partial void UpdateSupplierDCLookupWarehouse(SupplierDCLookupWarehouse instance);
    partial void DeleteSupplierDCLookupWarehouse(SupplierDCLookupWarehouse instance);
    #endregion
		
		public WarehouseVendorsDataContext() : 
				base(global::Spar.Gateway.VendorList.Properties.Settings.Default.SparConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WarehouseVendorsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WarehouseVendorsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WarehouseVendorsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WarehouseVendorsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<SupplierWarehouse> SupplierWarehouses
		{
			get
			{
				return this.GetTable<SupplierWarehouse>();
			}
		}
		
		public System.Data.Linq.Table<SupplierDCLookupWarehouse> SupplierDCLookupWarehouses
		{
			get
			{
				return this.GetTable<SupplierDCLookupWarehouse>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _RegistrationNumber;
		
		private string _VatNumber;
		
		private string _Address;
		
		private string _PostalAddress;
		
		private string _PhoneNumber;
		
		private string _FaxNumber;
		
		private string _Ean;
		
		private System.Guid _msrepl_tran_version;
		
		private string _X400;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnRegistrationNumberChanging(string value);
    partial void OnRegistrationNumberChanged();
    partial void OnVatNumberChanging(string value);
    partial void OnVatNumberChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPostalAddressChanging(string value);
    partial void OnPostalAddressChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnFaxNumberChanging(string value);
    partial void OnFaxNumberChanged();
    partial void OnEanChanging(string value);
    partial void OnEanChanged();
    partial void Onmsrepl_tran_versionChanging(System.Guid value);
    partial void Onmsrepl_tran_versionChanged();
    partial void OnX400Changing(string value);
    partial void OnX400Changed();
    #endregion
		
		public Company()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMID", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcName", Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcRegNumber", Storage="_RegistrationNumber", DbType="VarChar(50)")]
		public string RegistrationNumber
		{
			get
			{
				return this._RegistrationNumber;
			}
			set
			{
				if ((this._RegistrationNumber != value))
				{
					this.OnRegistrationNumberChanging(value);
					this.SendPropertyChanging();
					this._RegistrationNumber = value;
					this.SendPropertyChanged("RegistrationNumber");
					this.OnRegistrationNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcVatNumber", Storage="_VatNumber", DbType="VarChar(50)")]
		public string VatNumber
		{
			get
			{
				return this._VatNumber;
			}
			set
			{
				if ((this._VatNumber != value))
				{
					this.OnVatNumberChanging(value);
					this.SendPropertyChanging();
					this._VatNumber = value;
					this.SendPropertyChanged("VatNumber");
					this.OnVatNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcAddress", Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcPostAddress", Storage="_PostalAddress", DbType="VarChar(50)")]
		public string PostalAddress
		{
			get
			{
				return this._PostalAddress;
			}
			set
			{
				if ((this._PostalAddress != value))
				{
					this.OnPostalAddressChanging(value);
					this.SendPropertyChanging();
					this._PostalAddress = value;
					this.SendPropertyChanged("PostalAddress");
					this.OnPostalAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcPhoneNum", Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcFaxNum", Storage="_FaxNumber", DbType="VarChar(50)")]
		public string FaxNumber
		{
			get
			{
				return this._FaxNumber;
			}
			set
			{
				if ((this._FaxNumber != value))
				{
					this.OnFaxNumberChanging(value);
					this.SendPropertyChanging();
					this._FaxNumber = value;
					this.SendPropertyChanged("FaxNumber");
					this.OnFaxNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcEANNumber", Storage="_Ean", DbType="VarChar(50)")]
		public string Ean
		{
			get
			{
				return this._Ean;
			}
			set
			{
				if ((this._Ean != value))
				{
					this.OnEanChanging(value);
					this.SendPropertyChanging();
					this._Ean = value;
					this.SendPropertyChanged("Ean");
					this.OnEanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msrepl_tran_version", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid msrepl_tran_version
		{
			get
			{
				return this._msrepl_tran_version;
			}
			set
			{
				if ((this._msrepl_tran_version != value))
				{
					this.Onmsrepl_tran_versionChanging(value);
					this.SendPropertyChanging();
					this._msrepl_tran_version = value;
					this.SendPropertyChanged("msrepl_tran_version");
					this.Onmsrepl_tran_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="CMcX400", Storage="_X400", DbType="NVarChar(13)")]
		public string X400
		{
			get
			{
				return this._X400;
			}
			set
			{
				if ((this._X400 != value))
				{
					this.OnX400Changing(value);
					this.SendPropertyChanging();
					this._X400 = value;
					this.SendPropertyChanged("X400");
					this.OnX400Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Supplier")]
	public partial class SupplierWarehouse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Email;
		
		private int _UserId;
		
		private string _Address;
		
		private System.Nullable<int> _SendMail;
		
		private System.Guid _msrepl_tran_version;
		
		private string _Comments;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnUserIdChanging(int value);
    partial void OnUserIdChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnSendMailChanging(System.Nullable<int> value);
    partial void OnSendMailChanged();
    partial void Onmsrepl_tran_versionChanging(System.Guid value);
    partial void Onmsrepl_tran_versionChanged();
    partial void OnCommentsChanging(string value);
    partial void OnCommentsChanged();
    #endregion
		
		public SupplierWarehouse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SPID", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SPcName", Storage="_Name", DbType="VarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SPcEMail", Storage="_Email", DbType="VarChar(1000)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SPiUserID", Storage="_UserId", DbType="Int NOT NULL")]
		public int UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SPcAddress", Storage="_Address", DbType="VarChar(100)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="SPiSendMail", Storage="_SendMail", DbType="Int")]
		public System.Nullable<int> SendMail
		{
			get
			{
				return this._SendMail;
			}
			set
			{
				if ((this._SendMail != value))
				{
					this.OnSendMailChanging(value);
					this.SendPropertyChanging();
					this._SendMail = value;
					this.SendPropertyChanged("SendMail");
					this.OnSendMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msrepl_tran_version", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid msrepl_tran_version
		{
			get
			{
				return this._msrepl_tran_version;
			}
			set
			{
				if ((this._msrepl_tran_version != value))
				{
					this.Onmsrepl_tran_versionChanging(value);
					this.SendPropertyChanging();
					this._msrepl_tran_version = value;
					this.SendPropertyChanged("msrepl_tran_version");
					this.Onmsrepl_tran_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comments", DbType="NVarChar(MAX)")]
		public string Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				if ((this._Comments != value))
				{
					this.OnCommentsChanging(value);
					this.SendPropertyChanging();
					this._Comments = value;
					this.SendPropertyChanged("Comments");
					this.OnCommentsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SupplierDCLookup")]
	public partial class SupplierDCLookupWarehouse : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _BuEanCode;
		
		private string _VendorCode;
		
		private System.Nullable<char> _VendorStatus;
		
		private string _VendorName;
		
		private string _Address1;
		
		private string _Address2;
		
		private string _Address3;
		
		private string _PostalCode;
		
		private string _PhoneNumber;
		
		private string _CountryCode;
		
		private string _LocationCode;
		
		private string _DespatchPoint;
		
		private string _EmailAddress;
		
		private string _SupplierVatNumber;
		
		private System.Nullable<char> _CaptureClaim;
		
		private System.DateTime _UpdateDate;
		
		private System.Nullable<int> _CannotMatch;
		
		private string _VendorAccountType;
		
		private string _StoreOrderMethod;
		
		private string _SupplierOrderMethod;
		
		private string _OrderEmailAddress;
		
		private string _EdiGroupCode;
		
		private string _EdiGroupCodeEan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnBuEanCodeChanging(string value);
    partial void OnBuEanCodeChanged();
    partial void OnVendorCodeChanging(string value);
    partial void OnVendorCodeChanged();
    partial void OnVendorStatusChanging(System.Nullable<char> value);
    partial void OnVendorStatusChanged();
    partial void OnVendorNameChanging(string value);
    partial void OnVendorNameChanged();
    partial void OnAddress1Changing(string value);
    partial void OnAddress1Changed();
    partial void OnAddress2Changing(string value);
    partial void OnAddress2Changed();
    partial void OnAddress3Changing(string value);
    partial void OnAddress3Changed();
    partial void OnPostalCodeChanging(string value);
    partial void OnPostalCodeChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnCountryCodeChanging(string value);
    partial void OnCountryCodeChanged();
    partial void OnLocationCodeChanging(string value);
    partial void OnLocationCodeChanged();
    partial void OnDespatchPointChanging(string value);
    partial void OnDespatchPointChanged();
    partial void OnEmailAddressChanging(string value);
    partial void OnEmailAddressChanged();
    partial void OnSupplierVatNumberChanging(string value);
    partial void OnSupplierVatNumberChanged();
    partial void OnCaptureClaimChanging(System.Nullable<char> value);
    partial void OnCaptureClaimChanged();
    partial void OnUpdateDateChanging(System.DateTime value);
    partial void OnUpdateDateChanged();
    partial void OnCannotMatchChanging(System.Nullable<int> value);
    partial void OnCannotMatchChanged();
    partial void OnVendorAccountTypeChanging(string value);
    partial void OnVendorAccountTypeChanged();
    partial void OnStoreOrderMethodChanging(string value);
    partial void OnStoreOrderMethodChanged();
    partial void OnSupplierOrderMethodChanging(string value);
    partial void OnSupplierOrderMethodChanged();
    partial void OnOrderEmailAddressChanging(string value);
    partial void OnOrderEmailAddressChanged();
    partial void OnEdiGroupCodeChanging(string value);
    partial void OnEdiGroupCodeChanged();
    partial void OnEdiGroupCodeEanChanging(string value);
    partial void OnEdiGroupCodeEanChanged();
    #endregion
		
		public SupplierDCLookupWarehouse()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="sID", Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuEanCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string BuEanCode
		{
			get
			{
				return this._BuEanCode;
			}
			set
			{
				if ((this._BuEanCode != value))
				{
					this.OnBuEanCodeChanging(value);
					this.SendPropertyChanging();
					this._BuEanCode = value;
					this.SendPropertyChanged("BuEanCode");
					this.OnBuEanCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorCode", DbType="NVarChar(50)")]
		public string VendorCode
		{
			get
			{
				return this._VendorCode;
			}
			set
			{
				if ((this._VendorCode != value))
				{
					this.OnVendorCodeChanging(value);
					this.SendPropertyChanging();
					this._VendorCode = value;
					this.SendPropertyChanged("VendorCode");
					this.OnVendorCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorStatus", DbType="Char(1)")]
		public System.Nullable<char> VendorStatus
		{
			get
			{
				return this._VendorStatus;
			}
			set
			{
				if ((this._VendorStatus != value))
				{
					this.OnVendorStatusChanging(value);
					this.SendPropertyChanging();
					this._VendorStatus = value;
					this.SendPropertyChanged("VendorStatus");
					this.OnVendorStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorName", DbType="NVarChar(300)")]
		public string VendorName
		{
			get
			{
				return this._VendorName;
			}
			set
			{
				if ((this._VendorName != value))
				{
					this.OnVendorNameChanging(value);
					this.SendPropertyChanging();
					this._VendorName = value;
					this.SendPropertyChanged("VendorName");
					this.OnVendorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address1", DbType="NVarChar(100)")]
		public string Address1
		{
			get
			{
				return this._Address1;
			}
			set
			{
				if ((this._Address1 != value))
				{
					this.OnAddress1Changing(value);
					this.SendPropertyChanging();
					this._Address1 = value;
					this.SendPropertyChanged("Address1");
					this.OnAddress1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address2", DbType="NVarChar(100)")]
		public string Address2
		{
			get
			{
				return this._Address2;
			}
			set
			{
				if ((this._Address2 != value))
				{
					this.OnAddress2Changing(value);
					this.SendPropertyChanging();
					this._Address2 = value;
					this.SendPropertyChanged("Address2");
					this.OnAddress2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address3", DbType="NVarChar(100)")]
		public string Address3
		{
			get
			{
				return this._Address3;
			}
			set
			{
				if ((this._Address3 != value))
				{
					this.OnAddress3Changing(value);
					this.SendPropertyChanging();
					this._Address3 = value;
					this.SendPropertyChanged("Address3");
					this.OnAddress3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="NVarChar(10)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this.OnPostalCodeChanging(value);
					this.SendPropertyChanging();
					this._PostalCode = value;
					this.SendPropertyChanged("PostalCode");
					this.OnPostalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="NVarChar(20)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryCode", DbType="Char(3)")]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this.OnCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._CountryCode = value;
					this.SendPropertyChanged("CountryCode");
					this.OnCountryCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LocationCode", DbType="NVarChar(50)")]
		public string LocationCode
		{
			get
			{
				return this._LocationCode;
			}
			set
			{
				if ((this._LocationCode != value))
				{
					this.OnLocationCodeChanging(value);
					this.SendPropertyChanging();
					this._LocationCode = value;
					this.SendPropertyChanged("LocationCode");
					this.OnLocationCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DespatchPoint", DbType="NVarChar(50)")]
		public string DespatchPoint
		{
			get
			{
				return this._DespatchPoint;
			}
			set
			{
				if ((this._DespatchPoint != value))
				{
					this.OnDespatchPointChanging(value);
					this.SendPropertyChanging();
					this._DespatchPoint = value;
					this.SendPropertyChanged("DespatchPoint");
					this.OnDespatchPointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAddress", DbType="NVarChar(100)")]
		public string EmailAddress
		{
			get
			{
				return this._EmailAddress;
			}
			set
			{
				if ((this._EmailAddress != value))
				{
					this.OnEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._EmailAddress = value;
					this.SendPropertyChanged("EmailAddress");
					this.OnEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierVatNumber", DbType="NVarChar(50)")]
		public string SupplierVatNumber
		{
			get
			{
				return this._SupplierVatNumber;
			}
			set
			{
				if ((this._SupplierVatNumber != value))
				{
					this.OnSupplierVatNumberChanging(value);
					this.SendPropertyChanging();
					this._SupplierVatNumber = value;
					this.SendPropertyChanged("SupplierVatNumber");
					this.OnSupplierVatNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaptureClaim", DbType="Char(1)")]
		public System.Nullable<char> CaptureClaim
		{
			get
			{
				return this._CaptureClaim;
			}
			set
			{
				if ((this._CaptureClaim != value))
				{
					this.OnCaptureClaimChanging(value);
					this.SendPropertyChanging();
					this._CaptureClaim = value;
					this.SendPropertyChanged("CaptureClaim");
					this.OnCaptureClaimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateDate", DbType="DateTime NOT NULL")]
		public System.DateTime UpdateDate
		{
			get
			{
				return this._UpdateDate;
			}
			set
			{
				if ((this._UpdateDate != value))
				{
					this.OnUpdateDateChanging(value);
					this.SendPropertyChanging();
					this._UpdateDate = value;
					this.SendPropertyChanged("UpdateDate");
					this.OnUpdateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CannotMatch", DbType="Int")]
		public System.Nullable<int> CannotMatch
		{
			get
			{
				return this._CannotMatch;
			}
			set
			{
				if ((this._CannotMatch != value))
				{
					this.OnCannotMatchChanging(value);
					this.SendPropertyChanging();
					this._CannotMatch = value;
					this.SendPropertyChanged("CannotMatch");
					this.OnCannotMatchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VendorAccountType", DbType="VarChar(10)")]
		public string VendorAccountType
		{
			get
			{
				return this._VendorAccountType;
			}
			set
			{
				if ((this._VendorAccountType != value))
				{
					this.OnVendorAccountTypeChanging(value);
					this.SendPropertyChanging();
					this._VendorAccountType = value;
					this.SendPropertyChanged("VendorAccountType");
					this.OnVendorAccountTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StoreOrderMethod", DbType="NVarChar(10)")]
		public string StoreOrderMethod
		{
			get
			{
				return this._StoreOrderMethod;
			}
			set
			{
				if ((this._StoreOrderMethod != value))
				{
					this.OnStoreOrderMethodChanging(value);
					this.SendPropertyChanging();
					this._StoreOrderMethod = value;
					this.SendPropertyChanged("StoreOrderMethod");
					this.OnStoreOrderMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierOrderMethod", DbType="NVarChar(10)")]
		public string SupplierOrderMethod
		{
			get
			{
				return this._SupplierOrderMethod;
			}
			set
			{
				if ((this._SupplierOrderMethod != value))
				{
					this.OnSupplierOrderMethodChanging(value);
					this.SendPropertyChanging();
					this._SupplierOrderMethod = value;
					this.SendPropertyChanged("SupplierOrderMethod");
					this.OnSupplierOrderMethodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderEmailAddress", DbType="NVarChar(50)")]
		public string OrderEmailAddress
		{
			get
			{
				return this._OrderEmailAddress;
			}
			set
			{
				if ((this._OrderEmailAddress != value))
				{
					this.OnOrderEmailAddressChanging(value);
					this.SendPropertyChanging();
					this._OrderEmailAddress = value;
					this.SendPropertyChanged("OrderEmailAddress");
					this.OnOrderEmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EdiGroupCode", DbType="NVarChar(10)")]
		public string EdiGroupCode
		{
			get
			{
				return this._EdiGroupCode;
			}
			set
			{
				if ((this._EdiGroupCode != value))
				{
					this.OnEdiGroupCodeChanging(value);
					this.SendPropertyChanging();
					this._EdiGroupCode = value;
					this.SendPropertyChanged("EdiGroupCode");
					this.OnEdiGroupCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EdiGroupCodeEan", DbType="NVarChar(20)")]
		public string EdiGroupCodeEan
		{
			get
			{
				return this._EdiGroupCodeEan;
			}
			set
			{
				if ((this._EdiGroupCodeEan != value))
				{
					this.OnEdiGroupCodeEanChanging(value);
					this.SendPropertyChanging();
					this._EdiGroupCodeEan = value;
					this.SendPropertyChanged("EdiGroupCodeEan");
					this.OnEdiGroupCodeEanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
